language: ruby
gemfile:
  - Gemfile
  - test/config/gemfiles/Gemfile.rails-3.2.x
#  - test/config/gemfiles/Gemfile.rails-3.1.x
#  - test/config/gemfiles/Gemfile.rails-3.0.x
rvm:
  - 1.9.3
env:
  - DB=sqlite3
  - DB=mysql
  - DB=postgres
