sqlite3:
  database: ":memory:"
  adapter: sqlite3
  timeout: 500

mysql:
  adapter: mysql
  database: aws_unit
  username: root
  encoding: utf8

postgres:
  adapter: postgresql
  database: aws_unit
  username: postgres
  min_messages: warning

